In [16]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

In [4]:
data_file = "../data/raw/art_catalog.xlsx - catalog.csv"
df = pd.read_csv(data_file)
df.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
0,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Venus and Adonis,1574-88,"Oil on canvas, 68 x 95 cm","Fogg Art Museum, Harvard University, Cambridge",https://www.wga.hu/html/a/aachen/adonis.html,painting,mythological,German,1601-1650
1,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Allegory,1598,"Oil on copper, 56 x 47 cm","Alte Pinakothek, Munich",https://www.wga.hu/html/a/aachen/allegory.html,painting,mythological,German,1601-1650
2,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Allegory of Peace, Art and Abundance",1602,"Oil on canvas, 197 x 142 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/aachen/allegorz.html,painting,mythological,German,1601-1650
3,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Jupiter, Antiope and Cupid",1595-98,"Oil on copper, 31 x 21 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/antiope.html,painting,mythological,German,1601-1650
4,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Pallas Athena, Venus and Juno",1593,"Oil on canvas, 54 x 67 cm","Museum of Fine Arts, Boston",https://www.wga.hu/html/a/aachen/athena.html,painting,mythological,German,1601-1650

Selectionne uniquement les "FORM == painting""

In [10]:
df_paint = df[df["FORM"] == "painting"]
df_paint.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
0,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Venus and Adonis,1574-88,"Oil on canvas, 68 x 95 cm","Fogg Art Museum, Harvard University, Cambridge",https://www.wga.hu/html/a/aachen/adonis.html,painting,mythological,German,1601-1650
1,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Allegory,1598,"Oil on copper, 56 x 47 cm","Alte Pinakothek, Munich",https://www.wga.hu/html/a/aachen/allegory.html,painting,mythological,German,1601-1650
2,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Allegory of Peace, Art and Abundance",1602,"Oil on canvas, 197 x 142 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/aachen/allegorz.html,painting,mythological,German,1601-1650
3,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Jupiter, Antiope and Cupid",1595-98,"Oil on copper, 31 x 21 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/antiope.html,painting,mythological,German,1601-1650
4,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Pallas Athena, Venus and Juno",1593,"Oil on canvas, 54 x 67 cm","Museum of Fine Arts, Boston",https://www.wga.hu/html/a/aachen/athena.html,painting,mythological,German,1601-1650

In [ ]:
urls = list(df_paint["URL"])

urls[:5]

['https://www.wga.hu/html/a/aachen/adonis.html',
 'https://www.wga.hu/html/a/aachen/allegory.html',
 'https://www.wga.hu/html/a/aachen/allegorz.html',
 'https://www.wga.hu/html/a/aachen/antiope.html',
 'https://www.wga.hu/html/a/aachen/athena.html']

In [ ]:

output_dir = "../data/processed"
os.makedirs(output_dir, exist_ok=True) 

def download_wga_image(page_url, output_dir, sleep_time=1.5):
    img_path = page_url.replace("/html/", "/detail/")
    img_url = img_path.replace(".html", ".jpg")


    filename = os.path.join(output_dir, os.path.basename(img_url))


    if os.path.exists(filename):
        print(f"L'image existe déjà : {filename}, téléchargement ignoré.")
        return


    response = requests.get(img_url)
    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)
        print(f"Image téléchargée : {filename}")
        time.sleep(sleep_time)  
    else:
        print("Impossible de télécharger l'image :", response.status_code, img_url)

In [26]:
for url in urls:
    download_wga_image(url.strip(), output_dir)

L'image existe déjà : ../data/processed\adonis.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\allegory.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\allegorz.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\antiope.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\athena.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\bacchus.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\bacchus1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\davidbat.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\gods.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\gods1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\j_couple.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\k_couple.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\rudolf2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\selfpor1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\selfport.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\war.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\z_scene.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\deerlake.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\rosegard.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\michael.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\chimney1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\deerhunt.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\galerie1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\galerie2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\meeting.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\moses.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\orpheus.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\proserpi.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\scipio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\torfani1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\torfani2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\abbati1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\abbati2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\abbati3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\abbati4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\abbati5.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\cornaro.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\andria1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\andria2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\culmingh.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\philocte.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\firework.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\battle.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\hunt.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\ark.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\ark1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\ark2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\ark3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\chapel.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\lucca1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\lucca2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\lucca3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\siena1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\siena2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\siena3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\selfport.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\fishgame.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilfish.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilflow.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillife.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stiloyst.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\breakfas.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\deadbird.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\hunting.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\hunting2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stil_fru.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilbask.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilflow.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilfrui.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\still_fr.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\still_li.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillfru.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillif.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillife.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilliff.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillpar.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillpea.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilmous.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stilvase.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vasewatc.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\weapons.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\fruit.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\apostles.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\christ.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\christ_a.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\christ_m.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\cook.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\cook1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\egg-danc.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\fatkitch.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\market.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\market1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\marketsc.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\marketsd.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\marketse.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\marketst.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\meatsell.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\merry_co.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\pancake.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\peasant1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\peasant2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stillife.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\triptic1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\triptic2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\triptic3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vendor_f.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar31.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar32.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar33.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\altar34.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\natavit1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\sacred.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\dogstudy.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\gentlema.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\horse.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\playgrou.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\terriers.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\circumci.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\virgin_c.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\9th_wave.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\stormy.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\brothers.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\conversa.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vegetab1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vegetab2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\cardioti.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\congrega.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\figsaint.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1spring.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1spring1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\2summer.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\3autumn.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\4winter.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem1a.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem2a.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem3a.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5elem4a.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5verospi.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\6corsini.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\adonis.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\annuncia.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\dianaact.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\dianacte.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\holy_fam.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\holyfam.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\holyfami.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus0.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton5.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton6.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton7.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\phaeton8.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\apocaly.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\apocaly1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\apocaly2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\triptych.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\oratory.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\virtues.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\ceiling.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1mantua1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1mantua2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1mantua3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\adoratio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\virgin.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\virgin_c.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\visitat.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\visitat1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\visitat2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\visitat3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\visitat4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\campo.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\giuseppe.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\v_josefa.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\grapehar.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\flood.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\redsquar.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\view_stp.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\satire.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\satire1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\triumph.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\annuncia.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\crucifix.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\crucifiz.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\madchild.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\pieta.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\scenes.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\landmose.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\riverla1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\riverla2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1poggio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\2poggio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\3poggio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\4poggio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5poggio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\allegory.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\annuncia.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\b_christ.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\christia.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\gaddi1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\gaddi2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\holytrin.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\loggetta.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portra1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrai5.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\portrait.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\preachin.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\st_peter.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\studiolo.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\susanna.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vasari1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\vasari2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus_c.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\venus_cu.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\adoratio.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\judith.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\judith_h.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\judith_k.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\judith_p.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\judith_r.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\uriel.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\almatad1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\almatad2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\almatad3.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\almatad4.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\almatad5.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\extensiv.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\flight_e.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\skating.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\winter_l.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\winterla.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\viewvien.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\1satyr.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\2landsca.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\3danube.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\4susanna.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5battle.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5battle1.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\5battle2.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\6lovers.jpg, téléchargement ignoré.
L'image existe déjà : ../data/processed\7lot_dau.jpg, téléchargement ignoré.